# Welcome to Impatient-Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically.

# Site settings
title: Data Journalists
excerpt: Lista de periodistas, diseñadores y programadores, un proyecto ideado por Félix Arias y desarrollado por Miguel Carvajal.
email: diccionariodelcliche@gmail.com
# Build settings
markdown: kramdown

# Exclude nodes artifacts from build
exclude:
  - package.json
  - node_modules
  - gulpfile.js

# Postal address (add as many lines as necessary)
collections:
  cliches:
    output: true