# Welcome to Impatient-Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically.

# Site settings
title: Periodistas de datos
description: "Directorio de periodistas de datos en España y Latinoamérica. Perfiles, entrevistas y recursos sobre periodismo de datos, visualización y scraping en medios."
email: mcarvajal@umh.es
# Build settings
markdown: kramdown

collections:
  entrevistas:
    output: true
    permalink: /:collection/:name
    
# Exclude nodes artifacts from build
exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - _site

url: "https://periodistasdedatos.com"
repository: mipumh/djspain
twitter_username: #jekyllrb
github_username:  #jekyll

plugins:
  - jekyll-feed

sass:
    sass_dir: _sass
    style: compressed
